import { color } from 'framer-motion';
import type { Config } from 'tailwindcss';
const withMT = require('./node_modules/@material-tailwind/react/utils/withMT');

const config: Config = withMT({
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}',
    './node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      current: 'currentColor',
      transparent: 'transparent',
      primary: '#F2E857',
      secondary: '#F2C84B',
      accent: '#F26457',
      sub: '#F27052',
      background: '#2d2d2d',
      text: '#0D0D0D',
      white: '#ffffff',
      black: '#000000',
      'gray-100': '#F8F9FB',
      'gray-200': '#EFF1F4',
      'gray-250': '#E8E8E8',
      'gray-300': '#DBDEE3',
      'gray-400': '#BCC0C6',
      'gray-500': '#9FA3AB',
      'gray-600': '#717680',
      'gray-700': '#4B515B',
      'gray-800': '#363B44',
      'gray-900': '#292C36',
      'gray-1000': '#15181E',
      blue: undefined,
      purple: undefined,
      red: undefined,
      green: undefined,
      yellow: undefined,
      indigo: undefined,
      pink: undefined,
      rose: undefined,
      fuchsia: undefined,
      cyan: undefined,
      teal: undefined,
      orange: undefined,
      lime: undefined,
      emerald: undefined,
      sky: undefined,
      violet: undefined,
      amber: undefined,
      'light-blue': undefined,
      'light-green': undefined,
      coolGray: undefined,
      trueGray: undefined,
      warmGray: undefined,
      blueGray: undefined,
      slate: undefined,
      gray: undefined,
      zinc: undefined,
      neutral: undefined,
      stone: undefined,
      brown: undefined,
      'blue-gray': undefined,
      'deep-orange': undefined,
      'deep-purple': undefined,
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
});
export default config;
